<?php 
	use \Attachment\ATTACHMENT_SPECIFICS;

	add_theme_support( 'post-thumbnails' );
	add_theme_support('nav-menus');	
	add_theme_support('widgets');	

	add_image_size( ATTACHMENT_SPECIFICS::SLIDER_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::SLIDER_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::SLIDER_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::PRODUCT_589x567_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::PRODUCT_589x567_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::PRODUCT_589x567_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::PRODUCT_381x285_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::PRODUCT_381x285_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::PRODUCT_381x285_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::PRODUCT_357X268_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::PRODUCT_357X268_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::PRODUCT_357X268_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::PRODUCT_240x180_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::PRODUCT_240x180_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::PRODUCT_240x180_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::PRODUCT_196x147_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::PRODUCT_196x147_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::PRODUCT_196x147_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::PRODUCT_103x77_FEATURE_IMAGE, 
					ATTACHMENT_SPECIFICS::PRODUCT_103x77_FEATURE_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::PRODUCT_103x77_FEATURE_IMAGE_SIZES[1], 
					true );

	add_image_size( ATTACHMENT_SPECIFICS::ARTICLE_210x250_FEATURED_IMAGE, 
					ATTACHMENT_SPECIFICS::ARTICLE_210x250_FEATURED_IMAGE_SIZES[0], 
					ATTACHMENT_SPECIFICS::ARTICLE_210x250_FEATURED_IMAGE_SIZES[1], 
					true );