<?php 

    namespace Actions\Enqueues;

    class EnqueueLocalizeActionListsUtils {

        public static function render() {

           wp_localize_script('jquery', '__ACTIONS_HOOKS_LIST', array(

                'UNICORN_COMMERCANTS_UPDATE_COORDIATES_DATA_ACTION' => \Actions\ACTIONS::UNICORN_COMMERCANTS_UPDATE_COORDIATES_DATA_ACTION,

                'UNICORN_COMMERCANTS_UPDATE_MERCHANT_DATA_ACTION' => \Actions\ACTIONS::UNICORN_COMMERCANTS_UPDATE_MERCHANT_DATA_ACTION,

                'UNICORN_COMMERCANTS_IMPORT_MERCHANT_DATA_ACTION' => \Actions\ACTIONS::UNICORN_COMMERCANTS_IMPORT_MERCHANT_DATA_ACTION,

                'UNICORN_COMMERCANTS_IMPORT_CATEGORIES_DATA_ACTION' => \Actions\ACTIONS::UNICORN_COMMERCANTS_IMPORT_CATEGORIES_DATA_ACTION,

                'UNICORN_COMMERCANTS_UPDATE_CATEGORIES_DATA_ACTION' => \Actions\ACTIONS::UNICORN_COMMERCANTS_UPDATE_CATEGORIES_DATA_ACTION,

                'UNICORN_CREATE_NEW_STORE_ACCOUNT_ACTION' => \Actions\ACTIONS::UNICORN_CREATE_NEW_STORE_ACCOUNT_ACTION,

                'UNICORN_UPDATE_PROFILE_INFORMATION_ACTION' => \Actions\ACTIONS::UNICORN_UPDATE_PROFILE_INFORMATION_ACTION,

                'UNICORN_CHECK_USER_EMAIL_EXIST_ACTION' => \Actions\ACTIONS::UNICORN_CHECK_USER_EMAIL_EXIST_ACTION,

                'UNICORN_UPDATE_PRODUCT_ACTION' => \Actions\ACTIONS::UNICORN_UPDATE_PRODUCT_ACTION,

                'UNICORN_SHOP_FEEDBACK_ABUSE_PRODUCT_ACTION' => \Actions\ACTIONS::UNICORN_SHOP_FEEDBACK_ABUSE_PRODUCT_ACTION,

                'UNICORN_GET_PRODUCT_SLIDER_ACTION' => \Actions\ACTIONS::UNICORN_GET_PRODUCT_SLIDER_ACTION,

                'UNICORN_GET_SEARCHED_PRODUCTS_ACTION' => \Actions\ACTIONS::UNICORN_GET_SEARCHED_PRODUCTS_ACTION,

                'UNICORN_ADMIN_UPDATE_STORE_ACTION' => \Actions\ACTIONS::UNICORN_ADMIN_UPDATE_STORE_ACTION,
                
                'UNICORN_ADMIN_GET_DETAILS_FORM_STORE_ACTION' => \Actions\ACTIONS::UNICORN_ADMIN_GET_DETAILS_FORM_STORE_ACTION,

                'UNICORN_REMOVE_STORES_ACCOUNT_ACTION' => \Actions\ACTIONS::UNICORN_REMOVE_STORES_ACCOUNT_ACTION

           ));

        }

    }