<?php 

    namespace Actions\Enqueues;

    class EnqueueAdminLocalizeDtColumnsUtils {

        public static function render() {

            $dt_commercants_columns = array(
                'ID' => \DataTables\DT_COMMERCANTS_COLUMNS::ID,
                'ID_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::ID_IDX,
                'ENSEIGNE' => \DataTables\DT_COMMERCANTS_COLUMNS::ENSEIGNE,
                'ENSEIGNE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::ENSEIGNE_IDX,
                'SECTEUR_ACTIVITY' => \DataTables\DT_COMMERCANTS_COLUMNS::SECTEUR_ACTIVITY,
                'SECTEUR_ACTIVITY_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::SECTEUR_ACTIVITY_IDX,
                'NUMERO' => \DataTables\DT_COMMERCANTS_COLUMNS::NUMERO,
                'NUMERO_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::NUMERO_IDX,
                'ADDRESSE' => \DataTables\DT_COMMERCANTS_COLUMNS::ADDRESSE,
                'ADDRESSE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::ADDRESSE_IDX,
                'CODE_POSTAL' => \DataTables\DT_COMMERCANTS_COLUMNS::CODE_POSTAL,
                'CODE_POSTAL_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::CODE_POSTAL_IDX,
                'VILLE' => \DataTables\DT_COMMERCANTS_COLUMNS::VILLE,
                'VILLE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::VILLE_IDX,
                'TELEPHONE_COMMERCE' => \DataTables\DT_COMMERCANTS_COLUMNS::TELEPHONE_COMMERCE,
                'TELEPHONE_COMMERCE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::TELEPHONE_COMMERCE_IDX,
                'EMAIL_COMMERCE' => \DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_COMMERCE,
                'EMAIL_COMMERCE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_COMMERCE_IDX,
                'PORTABLE_RESPONSABLE' => \DataTables\DT_COMMERCANTS_COLUMNS::PORTABLE_RESPONSABLE,
                'PORTABLE_RESPONSABLE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::PORTABLE_RESPONSABLE_IDX,
                'EMAIL_RESPONSABLE' => \DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_RESPONSABLE,
                'EMAIL_RESPONSABLE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_RESPONSABLE_IDX,
                'SITE_INTERNET' => \DataTables\DT_COMMERCANTS_COLUMNS::SITE_INTERNET,
                'SITE_INTERNET_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::SITE_INTERNET_IDX,
                'PAGE_FACEBOOK' => \DataTables\DT_COMMERCANTS_COLUMNS::PAGE_FACEBOOK,
                'PAGE_FACEBOOK_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::PAGE_FACEBOOK_IDX,
                'JOURS_OUVERTURE_HIVER' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_OUVERTURE_HIVER,
                'JOURS_OUVERTURE_HIVER_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_OUVERTURE_HIVER_IDX,
                'HORAIRES_HIVER' => \DataTables\DT_COMMERCANTS_COLUMNS::HORAIRES_HIVER,
                'HORAIRES_HIVER_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::HORAIRES_HIVER_IDX,
                'JOURS_FERMETURE_HIVER' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_FERMETURE_HIVER,
                'JOURS_FERMETURE_HIVER_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_FERMETURE_HIVER_IDX,
                'JOURS_OUVERTURE_ETE' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_OUVERTURE_ETE,
                'JOURS_OUVERTURE_ETE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_OUVERTURE_ETE_IDX,
                'HORAIRES_ETE' => \DataTables\DT_COMMERCANTS_COLUMNS::HORAIRES_ETE,
                'HORAIRES_ETE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::HORAIRES_ETE_IDX,
                'JOURS_FERMETURE_ETE' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_FERMETURE_ETE,
                'JOURS_FERMETURE_ETE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::JOURS_FERMETURE_ETE_IDX,
                'PARTICULARITES_HORAIRES' => \DataTables\DT_COMMERCANTS_COLUMNS::PARTICULARITES_HORAIRES,
                'PARTICULARITES_HORAIRES_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::PARTICULARITES_HORAIRES_IDX,
                'ANNUAIRE' => \DataTables\DT_COMMERCANTS_COLUMNS::ANNUAIRE,
                'ANNUAIRE_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::ANNUAIRE_IDX,
                'MASQUES_RESCUS' => \DataTables\DT_COMMERCANTS_COLUMNS::MASQUES_RESCUS,
                'MASQUES_RESCUS_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::MASQUES_RESCUS_IDX,
                'BAIL_SAISONNIER' => \DataTables\DT_COMMERCANTS_COLUMNS::BAIL_SAISONNIER,
                'BAIL_SAISONNIER_IDX' => \DataTables\DT_COMMERCANTS_COLUMNS::BAIL_SAISONNIER_IDX,
            );        
        
            wp_localize_script( 'jquery', 'DT_COMMERCANTS_COLUMNS', $dt_commercants_columns );
        

        }

    }