<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */

define('THEME_CHILD_DIR', WP_CONTENT_DIR  . '/themes/dealsdot-child');
    
define('THEME_CHILD_DIR_URI', str_replace(ABSPATH, "//{$_SERVER['SERVER_NAME']}/", WP_CONTENT_DIR  . '/themes/dealsdot-child'));

function localize_message_notifications() {

    wp_localize_script('jquery', 'MESSAGE_NOTIFICATIONS', MessageNotification\MessageGetUtils::get_all());

}

add_action(  'wp_enqueue_scripts', 'localize_message_notifications', 10 );
add_action(  'admin_enqueue_scripts', 'localize_message_notifications', 10 );

function dealsdot_remove_all_default_google_fonts() {

	wp_dequeue_style('rs-roboto');
    wp_dequeue_style('dealsdot-font-barlow');
    wp_dequeue_style('dealsdot-font-roboto');
    wp_dequeue_style('dealsdot-font-opensans');
    wp_dequeue_style('dealsdot-font-montserrat');

    wp_enqueue_style('dealsdot-font-raleway', 
    				 '//fonts.googleapis.com/css2?family=Raleway:wght@100;400;700&display=swap',
    				 array( 'dealsdot-style' ),
    				 wp_get_theme()->get('Version') );    
    
}

add_action('wp_enqueue_scripts', 'dealsdot_remove_all_default_google_fonts', 100);

 function remove_admin_login_header() {
   remove_action('wp_head', '_admin_bar_bump_cb');
}

 add_action('get_header', 'remove_admin_login_header');

 add_filter( 'show_admin_bar', '__return_false' ); 

 add_filter( 'send_password_change_email', '__return_false' );

require_once THEME_CHILD_DIR . '/constants/constants.php';

require_once THEME_CHILD_DIR . '/classes/actions/actions.php';

require_once THEME_CHILD_DIR . '/classes/page-templates/a/page-templates-class.php';

require_once THEME_CHILD_DIR . '/classes/attachments/attachments.php';

require_once THEME_CHILD_DIR . '/classes/commercants/commercants.php';

require_once THEME_CHILD_DIR . '/classes/datatables/datatables.php';

require_once THEME_CHILD_DIR . '/classes/mails/mails.php';

require_once THEME_CHILD_DIR . '/classes/message-notification/message-notification.php';

require_once THEME_CHILD_DIR . '/classes/paginations/paginations.php';

require_once THEME_CHILD_DIR . '/classes/products/products.php';

require_once THEME_CHILD_DIR . '/classes/stores/stores.php';

require_once THEME_CHILD_DIR . '/classes/shortcodes/shortcodes.php';

require_once THEME_CHILD_DIR . '/classes/strings/strings.php';

require_once THEME_CHILD_DIR . '/classes/theme_options/theme_options.php';

require_once THEME_CHILD_DIR . '/classes/urls/urls.php';

require_once THEME_CHILD_DIR . '/classes/users/users.php';

require_once THEME_CHILD_DIR . '/classes/searchs/searchs.php';

require_once THEME_CHILD_DIR  . '/theme_settings/custom_post_types/options.php';
require_once THEME_CHILD_DIR . '/theme_settings/theme_options/options.php';
require_once THEME_CHILD_DIR . '/theme_settings/metaboxes/options.php';

require_once THEME_CHILD_DIR . '/extras/page-commercants/commercants.php';

function print_log_stores_not_accounts() {

    //echo var_dump(filter_var('nlecuyer@perrin-ravioli.com', FILTER_VALIDATE_EMAIL)); die();

    $data_stores_listing = \Commercants\CommercantGetListUtils::get();

    $email_idx = \DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_COMMERCE;   
    
    $count = 0;

    foreach ( $data_stores_listing as $key => $data_store ) :

        $store_account = get_user_by_email($data_store[$email_idx]);        

        if ( $store_account ) :

        else :    
            
            /*$count++;

            $numero = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::NUMERO];
            $ville = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::VILLE];
            $addresse = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::ADDRESSE];
            $telephone_commerce = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::TELEPHONE_COMMERCE];
            $secteur_activity = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::SECTEUR_ACTIVITY];
            $enseigne = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::ENSEIGNE];
            $code_postal = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::CODE_POSTAL];
            $email = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_COMMERCE];          

            file_put_contents("print_log_stores_not_accounts.log", 
                              "{$count}> Enseigne: {$enseigne} - 
                               Secteur activity: {$secteur_activity} - 
                               numero: {$numero} - 
                               ville: {$ville} - 
                               addresse: {$addresse} - 
                               code postal : {$code_postal} - 
                               email : {$email}" . PHP_EOL . PHP_EOL, FILE_APPEND | LOCK_EX);*/ 

            $numero = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::NUMERO];
            $ville = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::VILLE];
            $addresse = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::ADDRESSE];
            $telephone_commerce = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::TELEPHONE_COMMERCE];
            $secteur_activity = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::SECTEUR_ACTIVITY];
            $enseigne = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::ENSEIGNE];
            $code_postal = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::CODE_POSTAL];

            $horaires_hiver = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::HORAIRES_HIVER];
            $jours_ouverture_hiver = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::JOURS_OUVERTURE_HIVER];
            $jours_fermeture_hiver = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::JOURS_FERMETURE_HIVER];
            $horaires_ete = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::HORAIRES_ETE];
            $jours_ouverture_ete = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::JOURS_OUVERTURE_ETE];
            $jours_fermeture_ete = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::JOURS_FERMETURE_ETE];
            $particularites_horaires = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::PARTICULARITES_HORAIRES];

            $email = $data_store[\DataTables\DT_COMMERCANTS_COLUMNS::EMAIL_COMMERCE];

            if ( filter_var($email, FILTER_VALIDATE_EMAIL) || 
                    FALSE !== strpos($email, '@') ) :  
                
                $pieces = explode("@", $email);

                $store_login = $pieces[0] . '-' . $pieces[1];                

                $data = array(	
            
                        \Stores\STORE_DATA_FIELDS::STORE_FIRST_NAME => '',
                        \Stores\STORE_DATA_FIELDS::STORE_LAST_NAME => '',
                        \Stores\STORE_DATA_FIELDS::STORE_LOGIN => $store_login,
                        \Stores\STORE_DATA_FIELDS::STORE_DISPLAY_NAME => '',
                        \Stores\STORE_DATA_FIELDS::STORE_EMAIL => $email,
                        \Stores\STORE_DATA_FIELDS::STORE_MANAGER_PHONE => $telephone_commerce,			
                        \Stores\STORE_DATA_FIELDS::STORE_CIVILITY => '',
                        \Stores\STORE_DATA_FIELDS::STORE_SHOP_NAME => $enseigne,
                        \Stores\STORE_DATA_FIELDS::STORE_MAIN_CATEGORY => '',
                        \Stores\STORE_DATA_FIELDS::STORE_DESCRIPTION => '',
                        \Stores\STORE_DATA_FIELDS::STORE_WINTER_SCHEDULE => $horaires_hiver,
                        \Stores\STORE_DATA_FIELDS::STORE_WINTER_OPENING_DAY => $jours_ouverture_hiver,
                        \Stores\STORE_DATA_FIELDS::STORE_WINTER_CLOSING_DAY => $jours_fermeture_hiver,
                        \Stores\STORE_DATA_FIELDS::STORE_SUMMER_SCHEDULE => $horaires_ete,
                        \Stores\STORE_DATA_FIELDS::STORE_SUMMER_OPENING_DAY => $jours_ouverture_ete,
                        \Stores\STORE_DATA_FIELDS::STORE_SUMMER_CLOSING_DAY => $jours_fermeture_ete,
                        \Stores\STORE_DATA_FIELDS::STORE_SPECIAL_SCHEDULE => $particularites_horaires,
                        \Stores\STORE_DATA_FIELDS::STORE_CLICK_AND_COLLECT => '',
                        \Stores\STORE_DATA_FIELDS::STORE_DELIVERY => '',
                        \Stores\STORE_DATA_FIELDS::STORE_SPECIAL_DELIVERY_INFO => '',
                        \Stores\STORE_DATA_FIELDS::STORE_PICTURES => '',
                        \Stores\STORE_DATA_FIELDS::STORE_GEOLOCATION => '',
                        \Stores\STORE_DATA_FIELDS::STORE_ADDRESS => $adresse,
                        \Stores\STORE_DATA_FIELDS::STORE_POSTAL_CODE => $code_postal,
                        \Stores\STORE_DATA_FIELDS::STORE_CITY => $ville,
                        \Stores\STORE_DATA_FIELDS::STORE_EMAIL_ADDRESS_1 => '',
                        \Stores\STORE_DATA_FIELDS::STORE_EMAIL_ADDRESS_2 => '',
                        \Stores\STORE_DATA_FIELDS::STORE_PHONE => $telephone_commerce,
                        \Stores\STORE_DATA_FIELDS::STORE_WEBSITE => '',
                        \Stores\STORE_DATA_FIELDS::STORE_CHER => \Stores\STORE_DATA::STORE_CHER_AUTO,
                        \Stores\STORE_DATA_FIELDS::STORE_ACTION => \Stores\STORE_DATA::STORE_NEW_ACTION
            
                    );

                /*echo "<pre>";

                print_r($data);

                die();*/

                \Users\UserCreateUtils::create($data);

            endif;

        endif;

    endforeach;    
    
}

//add_action("init", "print_log_stores_not_accounts");

function print_log_store_has_attributes() {

    $args = array(

        \Users\USER_DATA_FIELDS::USER_ROLE => \Users\USER_ROLES::EDITOR_ROLE,

        'meta_query' => array(

            'store_click_and_collect_query' => array(
                'key' => \Stores\STORE_FIELDS::STORE_CLICK_AND_COLLECT_FIELD,                
                'value' => array(' ', '-1'),
                'compare' => 'NOT IN'    
            ),

            'delivery_query' => array(
                'key' => \Stores\STORE_FIELDS::STORE_DELIVERY_FIELD,    
                'value' => array(' ', '-1'),            
                'compare' => 'NOT IN'    
            ),

            'relation' => 'AND'

        )
        
    );

    $listings = get_users($args);    

    $count = 1;

    foreach ( $listings as $key => $store ) :

        $id = $store->ID;

        $shop_name = \Stores\StoreGetMetaShopNameUtils::get($id);
        $address = \Stores\StoreGetMetaAddressUtils::get($id);
        $clickandcollect = \Stores\StoreGetMetaCollectAndClickUtils::get($id);
        $delivery = \Stores\StoreGetMetaDeliveryUtils::get($id);

        file_put_contents("debug-stores-has-attributes.log", 
                            "{$count}> Enseigne: {$shop_name} - 
                                       Address: {$address} - 
                                       Click & Collect: {$clickandcollect} - 
                                       Livrations: {$delivery}" . PHP_EOL . PHP_EOL, 
                            FILE_APPEND | LOCK_EX);

        $count++;

    endforeach;

}

//add_action("init", "print_log_store_has_attributes");